# Usa la imagen base de Debian
FROM debian

# Actualiza los repositorios e instala Apache2
RUN apt-get update && apt-get install -y apache2

# Agrega cualquier otra configuración o comandos necesarios

# Indica que Apache2 se ha instalado correctamente
RUN echo "Apache2 ha sido instalado con éxito."

RUN sudo apt update

RUN sudo apt install nodejs -y

RUN echo "nodejs ha sido instalado con éxito."
